" Packages managed with vim-plug; run :PlugInstall to install packages and get
" Vim nicely set up
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Can't have comments in the plug section, I guess
call plug#begin()
Plug 'mattn/emmet-vim'
Plug 'scrooloose/nerdcommenter'
Plug 'scrooloose/nerdtree'
Plug 'airblade/vim-gitgutter'
Plug 'airblade/vim-rooter'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'neoclide/coc.nvim',
Plug 'cespare/vim-toml'
Plug 'stephpy/vim-yaml'
Plug 'rust-lang/rust.vim'
Plug 'toyamarinyon/vim-swift'
call plug#end()

" Status line content
set statusline=
set statusline+=%f
set statusline+=%m
set statusline+=%=
set statusline+=\ %y
set statusline+=\ %{&fileencoding?&fileencoding:&encoding}
set statusline+=\[%{&fileformat}\]
set statusline+=\ %p%%
set statusline+=\ %l:%c
set statusline+="\ "

" Show status line
set laststatus=2

" Show partial command in status line
set showcmd

" Mouse in all modes (=a gets it to work with tmux's mouse mode)
set mouse=a

" Status line colors
hi StatusLine ctermfg=208 ctermbg=234
hi StatusLineNC ctermfg=234 ctermbg=254

autocmd! InsertEnter * hi StatusLine ctermfg=220 ctermbg=234
autocmd! InsertLeave * hi StatusLine ctermfg=208 ctermbg=234

" Backspace should work like other programs
set backspace=indent,eol,start

" Set line numbers
autocmd! InsertEnter * set relativenumber number
autocmd! InsertLeave * set relativenumber number
highlight LineNr ctermfg=238 "line numbers are super dark gray

" Color for the tildes after the end of the buffer
hi EndOfBuffer ctermfg=238

hi VertSplit ctermbg=0 ctermfg=234

" Tab bar colors
hi TabLineFill ctermfg=0
hi TabLine ctermbg=0
hi TabLine ctermfg=254
hi TabLineSel ctermfg=208

" Set the leader key to comma instead of backslash
let mapleader = ","

" Whenever I write to my vimrc, I want to source it as well to instantly see
" what I've done
augroup myvimrchooks
	au!
	autocmd bufwritepost .vimrc source ~/.vimrc
	autocmd bufwritepost .vimrc source ~/.vim/vimrc
augroup END

" Pressing ,ev should open my vimrc for editing in a new tab.
nmap <Leader>ev :tabedit $MYVIMRC<cr>

" Scroll at seven lines of text from the bottom
set so=7

" Show matching brackets when the cursor is over them
set showmatch
set mat=2

" Highlight any characters that go over 80 columns
highlight ColorColumn ctermbg=red ctermfg=white
call matchadd('ColorColumn', '\%81v', 100)

" Permanent undo
set undodir=~/.vimdid
set undofile

" Auto indent, smart indent. I've commented out wrapping text because I'm not
" sure if I want text to wrap or not. We'll see.
set autoindent
set smartindent
set expandtab
set tabstop=4
set shiftwidth=4
set wrap
set linebreak

" Wrapping options
set formatoptions=tc " wrap text and comments using textwidth
set formatoptions+=r " continue comments when pressing ENTER in I mode
set formatoptions+=q " enable formatting of comments with gq
set formatoptions+=n " detect lists for formatting
set formatoptions+=b " auto-wrap in insert mode, and do not wrap old long lines

" Special stuff for git commit editing
autocmd FileType gitcommit highlight ColorColumn ctermbg=238
autocmd FileType gitcommit set textwidth=72
autocmd FileType gitcommit set colorcolumn=73
autocmd FileType gitcommit set colorcolumn+=51

" Pressing ,<space> should un-highlight my most recent search
nmap <Leader><space> :nohlsearch <CR>

" Other search options to make it more
set hlsearch
set ignorecase
set smartcase
set incsearch

" Make operations like yank, delete and paste work with the macOS
" clipboard
set clipboard=unnamed

" Pressing jk in rapid succession takes me out of insert mode. This is the
" most helpful vim thing I've ever done.
imap jk <esc>

" Let j and k work over long, wrapped lines of text (doesn't really do
" anything if set wrap isn't on)
map j gj
map k gk

" Remap tab and split commands
nnoremap <Tab> :tabn<CR>
nnoremap <S-Tab> :tabp<CR>
nnoremap <Bar> :vsplit<CR>
nnoremap _ :split<CR>
nnoremap J <C-W>j
nnoremap K <C-W>k
nnoremap H <C-W>h
nnoremap L <C-W>l

set splitbelow
set splitright

" Copy to osx clipboard
 vnoremap <C-c> "*y<CR>
 vnoremap y "*y<CR>
 nnoremap Y "*Y<CR>

" Get rid of all bells because silence > bells
set noerrorbells visualbell t_vb=
autocmd GUIEnter * set visualbell t_vb=

" Remove trailing whitespace on save
autocmd BufRead,BufWrite * if ! &bin | silent! %s/\s\+$//ge | endif

" Ctrl-P mappings
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'

" https://github.com/ctrlpvim/ctrlp.vim#basic-options
let g:ctrlp_working_path_mode = 'ra'

" Open NERDTree automatically if you start up with $ vim
" in a directory
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

" Automatically toggle paste if we're pasting from the clipboard
let &t_SI .= "\<Esc>[?2004h"
let &t_EI .= "\<Esc>[?2004l"

inoremap <special> <expr> <Esc>[200~ XTermPasteBegin()

function! XTermPasteBegin()
  set pastetoggle=<Esc>[201~
  set paste
  return ""
endfunction
