#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

require_installer package-manager
# require_installer ruby
# require_installer python
require_installer node

function install_neovim_mac() {
  if ! brew_is_tapped "neovim/neovim"; then
    brew_tap neovim/neovim
  fi

  brew_install neovim --HEAD
}

function install_neovim() {
  if [[ is_macos || is_macos_arm ]]; then
    install_neovim_mac
  else
    echo "hi"
    # install_neovim_linux
  fi
}

function setup_neovim_config() {
  mkdir -p ~/.config
  symlink_dotfile nvim ~/.config/nvim
}

function ensure_plugin_directory() {
  mkdir -p ~/.local/share/nvim/plugged
}

function install_proximity_sort() {
  if ! command_exists "proximity-sort" ; then
    cargo install --force proximity-sort
  fi
}

function install_bat() {
  brew_install bat

  mkdir -p ~/.config/bat
  symlink_dotfile bat/config ~/.config/bat/config
}

function install_lua_language_server() {
  brew_install ninja

  local lspdir="$HOME/.local/nvim/lsp"
  local location="$lspdir/lua-language-server"

  if [ ! -d "$location" ]; then
    dotsay "@b@blue[[+ Installing sumneko Lua LSP]]"

    mkdir -p "$lspdir"
    git clone https://github.com/sumneko/lua-language-server "$location"

    cd "$location" || exit 1
    git checkout tags/1.14.2 -b install-1.14.2
    git submodule update --init --recursive

    cd 3rd/luamake || exit 1
    ninja -f ninja/macos.ninja
    cd ../.. || exit 1
    ./3rd/luamake/luamake rebuild
  fi
}

dotheader "Setting up Neovim..."

install_lua_language_server
install_neovim
setup_neovim_config
ensure_plugin_directory
install_proximity_sort
install_bat
