#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

require_installer package-manager

dotheader "Setting up Hammerspoon..."
# brew_cask_install hammerspoon --appdir=/Applications


function install_spoon() {
  local spoon_name=$1
  local url="https://github.com/Hammerspoon/Spoons/raw/master/Spoons/$spoon_name.spoon.zip"
  local destination=/tmp/$spoon_name.spoon.zip
  local spoons_dir=$HOME/.hammerspoon/Spoons

  mkdir -p "$spoons_dir"

  if [ ! -d "$spoons_dir/$spoon_name.spoon" ]; then
    dotsay "@blue@b[[+ installing $spoon_name.spoon ]]"

    wget -nv $url -O $destination
    unzip -d $spoons_dir $destination
  else
    dotsay "+ $spoon_name.spoon already setup"
  fi
}

function install_hyperkey() {
  local spoons_dir=$HOME/.hammerspoon/Spoons
  mkdir -p "$spoons_dir"
  if [ ! -d "$spoons_dir/HyperKey.spoon" ]; then
    git clone https://github.com/dbalatero/HyperKey.spoon.git ~/.hammerspoon/Spoons/HyperKey.spoon
  fi
}

brew_install lua
brew_install luarocks

# bluetooth
brew_install blueutil

# brew_cask_install karabiner-elements
symlink_dotfile karabiner ~/.config/karabiner

luarocks install loop
luarocks install dkjson
luarocks install inspect
luarocks install --server=http://luarocks.org/dev lua-lsp
luarocks install luacheck
luarocks install lcf

symlink_dotfile hammerspoon ~/.hammerspoon
install_spoon SpoonInstall
install_hyperkey