#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

if is_macos; then
  if test ! $(which brew); then
    echo "Installing homebrew"

    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    if [ -f /opt/homebrew/bin/brew ]; then
        eval "$(/opt/homebrew/bin/brew shellenv)"
    fi

    brew update
  fi

  dotheader "Setting up Homebrew..."
elif is_linux; then
  dotheader "Setting up Aptitude..."

  apt_install aptitude
fi