#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

require_installer package-manager

function setup_zsh_symlinks() {
  symlink_dotfile zsh/zshrc ~/.zshrc
  symlink_dotfile zsh/custom ~/.zsh/custom
  symlink_dotfile zsh/vendor ~/.zsh/vendor
}

function zsh_binary() {
  if is_linux; then
    echo /bin/zsh
  elif is_macos_x86; then
    echo /usr/local/bin/zsh
  elif is_macos_arm; then
    echo /opt/homebrew/bin/zsh
  fi
}

function update_shell_whitelist() {
  local zshbin=$(zsh_binary)
  if ! cat /etc/shells | grep -q $zshbin; then
    echo "Adding $zshbin to /etc/shells, please enter your sudo password"

    echo $zshbin | sudo tee -a /etc/shells > /dev/null
  fi
}

function chsh_zsh() {
  echo $SHELL
  echo $(zsh_binary)
  if [[ "$SHELL" != "$(zsh_binary)" ]]; then
    local current_user=$USER
    dotsay "@b@blue[[Changing shell for $current_user...]]"
    sudo chsh -s $(zsh_binary) $current_user
  fi
}

function install_fzf() {
  brew_install fzf

  if [ ! -f $HOME/.fzf.zsh ]; then
    $(brew --prefix)/opt/fzf/install --no-update-rc --key-bindings --completion
  fi
}

function install_pure() {
  local puredirectory="$(dotfiles_location)/zsh/vendor"
  git clone https://github.com/sindresorhus/pure.git "$puredirectory/pure"
}

function install_antigen() {
  local plugin_file=$HOME/.zsh/vendor/antigen.zsh

  if [ ! -f $plugin_file ]; then
    echo "Installing antigen"
    curl -L git.io/antigen > "$plugin_file"
  fi
}

dotheader "Setting up ZSH..."

brew_install exa
brew_install neofetch

install_pure

install_package zsh
install_package zsh-completions

install_fzf

setup_zsh_symlinks
install_antigen

update_shell_whitelist
chsh_zsh
